create table if not exists public.proveedores (
    codigo_tienda text primary key,
    nombre_tienda text not null,
    direccion_proveedor text not null default '-',
    telefono text not null default '-',
    observacion text,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint proveedores_codigo_tienda_check check (btrim(codigo_tienda) <> ''),
    constraint proveedores_nombre_tienda_check check (btrim(nombre_tienda) <> '')
);

drop trigger if exists trg_proveedores_updated_at on public.proveedores;

create trigger trg_proveedores_updated_at
before update on public.proveedores
for each row
execute function public.fn_actualizar_updated_at();

alter table public.inventario_hilos
add column if not exists codigo_tienda text,
add column if not exists precio_compra numeric(12, 2) not null default 0,
add column if not exists fecha_compra date,
add column if not exists detalle_compra text;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'inventario_hilos_codigo_tienda_fkey'
          and conrelid = 'public.inventario_hilos'::regclass
    ) then
        alter table public.inventario_hilos
        add constraint inventario_hilos_codigo_tienda_fkey
        foreign key (codigo_tienda)
        references public.proveedores(codigo_tienda)
        on update cascade
        on delete restrict;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'inventario_hilos_precio_compra_check'
          and conrelid = 'public.inventario_hilos'::regclass
    ) then
        alter table public.inventario_hilos
        add constraint inventario_hilos_precio_compra_check
        check (precio_compra >= 0);
    end if;
end;
$$;

alter table public.pelones
add column if not exists porcentaje integer not null default 50,
add column if not exists codigo_tienda text,
add column if not exists precio_compra numeric(12, 2) not null default 0,
add column if not exists fecha_compra date,
add column if not exists detalle_compra text;

update public.pelones
set porcentaje = case estado
    when 'casi nada' then 8
    when 'poco' then 25
    when 'normal' then 55
    when 'mucho' then 75
    when 'completo' then 100
    else porcentaje
end
where porcentaje = 50;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'pelones_porcentaje_check'
          and conrelid = 'public.pelones'::regclass
    ) then
        alter table public.pelones
        add constraint pelones_porcentaje_check
        check (porcentaje between 0 and 100);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'pelones_codigo_tienda_fkey'
          and conrelid = 'public.pelones'::regclass
    ) then
        alter table public.pelones
        add constraint pelones_codigo_tienda_fkey
        foreign key (codigo_tienda)
        references public.proveedores(codigo_tienda)
        on update cascade
        on delete restrict;
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'pelones_precio_compra_check'
          and conrelid = 'public.pelones'::regclass
    ) then
        alter table public.pelones
        add constraint pelones_precio_compra_check
        check (precio_compra >= 0);
    end if;
end;
$$;

create table if not exists public.compras_hilos (
    id_compra_hilo bigint generated by default as identity primary key,
    id_hilo bigint references public.inventario_hilos(id_hilo) on delete set null,
    codigo_hilo_snapshot text not null,
    nombre_color_snapshot text not null,
    codigo_tienda text not null references public.proveedores(codigo_tienda) on update cascade on delete restrict,
    cantidad integer not null,
    precio_unitario numeric(12, 2) not null,
    total_compra numeric(12, 2) generated always as (cantidad::numeric * precio_unitario) stored,
    fecha_compra date not null default current_date,
    detalle_compra text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint compras_hilos_cantidad_check check (cantidad > 0),
    constraint compras_hilos_precio_unitario_check check (precio_unitario >= 0)
);

drop trigger if exists trg_compras_hilos_updated_at on public.compras_hilos;

create trigger trg_compras_hilos_updated_at
before update on public.compras_hilos
for each row
execute function public.fn_actualizar_updated_at();

create index if not exists idx_proveedores_nombre_tienda
on public.proveedores (nombre_tienda);

create index if not exists idx_inventario_hilos_codigo_tienda
on public.inventario_hilos (codigo_tienda);

create index if not exists idx_inventario_hilos_prefijo_codigo
on public.inventario_hilos ((left(codigo_hilo, 2)));

create index if not exists idx_compras_hilos_fecha_compra
on public.compras_hilos (fecha_compra);

create index if not exists idx_compras_hilos_codigo_tienda
on public.compras_hilos (codigo_tienda);

create index if not exists idx_compras_hilos_id_hilo
on public.compras_hilos (id_hilo);

create or replace function public.fn_registrar_compra_hilo(
    p_id_hilo bigint,
    p_codigo_tienda text,
    p_cantidad integer,
    p_precio_unitario numeric,
    p_fecha_compra date default current_date,
    p_detalle_compra text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_hilo record;
    v_id_compra bigint;
begin
    if not public.fn_es_admin() then
        raise exception 'No autorizado';
    end if;

    if p_id_hilo is null then
        raise exception 'Selecciona un hilo valido';
    end if;

    if p_codigo_tienda is null or btrim(p_codigo_tienda) = '' then
        raise exception 'Selecciona un proveedor valido';
    end if;

    if p_cantidad is null or p_cantidad <= 0 then
        raise exception 'La cantidad debe ser mayor a cero';
    end if;

    if p_precio_unitario is null or p_precio_unitario < 0 then
        raise exception 'El precio no puede ser negativo';
    end if;

    if not exists (
        select 1
        from public.proveedores
        where codigo_tienda = p_codigo_tienda
          and activo = true
    ) then
        raise exception 'Proveedor no disponible';
    end if;

    select id_hilo, codigo_hilo, nombre_color
    into v_hilo
    from public.inventario_hilos
    where id_hilo = p_id_hilo
    for update;

    if not found then
        raise exception 'Hilo no encontrado';
    end if;

    insert into public.compras_hilos (
        id_hilo,
        codigo_hilo_snapshot,
        nombre_color_snapshot,
        codigo_tienda,
        cantidad,
        precio_unitario,
        fecha_compra,
        detalle_compra
    )
    values (
        v_hilo.id_hilo,
        v_hilo.codigo_hilo,
        v_hilo.nombre_color,
        p_codigo_tienda,
        p_cantidad,
        p_precio_unitario,
        coalesce(p_fecha_compra, current_date),
        nullif(btrim(coalesce(p_detalle_compra, '')), '')
    )
    returning id_compra_hilo into v_id_compra;

    update public.inventario_hilos
    set stock = stock + p_cantidad,
        codigo_tienda = p_codigo_tienda,
        precio_compra = p_precio_unitario,
        fecha_compra = coalesce(p_fecha_compra, current_date),
        detalle_compra = nullif(btrim(coalesce(p_detalle_compra, '')), '')
    where id_hilo = p_id_hilo;

    return v_id_compra;
end;
$$;

alter table public.proveedores enable row level security;
alter table public.compras_hilos enable row level security;

drop policy if exists "Admins gestionan proveedores" on public.proveedores;
drop policy if exists "Admins gestionan compras de hilos" on public.compras_hilos;

create policy "Admins gestionan proveedores"
on public.proveedores
for all
to authenticated
using (public.fn_es_admin())
with check (public.fn_es_admin());

create policy "Admins gestionan compras de hilos"
on public.compras_hilos
for all
to authenticated
using (public.fn_es_admin())
with check (public.fn_es_admin());

grant select, insert, update, delete on public.proveedores to authenticated;
grant select, insert, update, delete on public.compras_hilos to authenticated;
grant select, insert, update, delete on public.inventario_hilos to authenticated;
grant select, insert, update, delete on public.pelones to authenticated;
grant usage, select on sequence public.compras_hilos_id_compra_hilo_seq to authenticated;
revoke all on function public.fn_registrar_compra_hilo(bigint, text, integer, numeric, date, text) from public;
grant execute on function public.fn_registrar_compra_hilo(bigint, text, integer, numeric, date, text) to authenticated;

alter table public.proveedores replica identity full;
alter table public.compras_hilos replica identity full;
alter table public.inventario_hilos replica identity full;
alter table public.pelones replica identity full;

do $$
begin
    alter publication supabase_realtime add table public.proveedores;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.compras_hilos;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;
