create or replace function public.fn_actualizar_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.fn_es_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.admins
        where admins.user_id = auth.uid()
    );
$$;

alter table public.admins
add column if not exists rol text not null default 'admin';

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'admins_rol_check'
          and conrelid = 'public.admins'::regclass
    ) then
        alter table public.admins
        add constraint admins_rol_check
        check (rol in ('propietario', 'admin', 'trabajador', 'lectura'))
        not valid;
    end if;

    begin
        alter table public.admins validate constraint admins_rol_check;
    exception
        when others then null;
    end;
end;
$$;

create table if not exists public.sistema_clientes (
    id_cliente bigint generated by default as identity primary key,
    nombre_cliente text not null,
    documento text not null default '-',
    telefono text not null default '-',
    tipo_cliente text not null default 'Persona Natural',
    direccion text not null default '-',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.sistema_productos (
    id_producto bigint generated by default as identity primary key,
    orden_produccion text not null default '-',
    codigo_diseno text not null unique,
    stock integer not null default 0,
    nombre_producto text not null,
    precio numeric(12, 2) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint sistema_productos_stock_check check (stock >= 0),
    constraint sistema_productos_precio_check check (precio >= 0)
);

create table if not exists public.sistema_metodos_pago (
    id_metodo_pago bigint generated by default as identity primary key,
    nombre_metodo text not null unique,
    activo boolean not null default true,
    created_at timestamptz not null default now()
);

insert into public.sistema_metodos_pago (nombre_metodo)
values ('Efectivo'), ('Yape'), ('Plin'), ('Transferencia')
on conflict (nombre_metodo) do nothing;

create table if not exists public.sistema_ventas (
    id_venta bigint generated by default as identity primary key,
    id_cliente bigint not null references public.sistema_clientes(id_cliente),
    id_producto bigint not null references public.sistema_productos(id_producto),
    id_metodo_pago bigint not null references public.sistema_metodos_pago(id_metodo_pago),
    cantidad integer not null,
    precio_unitario numeric(12, 2) not null,
    total_venta numeric(12, 2) generated always as (cantidad * precio_unitario) stored,
    fecha_venta date not null default current_date,
    observacion text,
    anulada boolean not null default false,
    fecha_registro timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint sistema_ventas_cantidad_check check (cantidad > 0),
    constraint sistema_ventas_precio_check check (precio_unitario >= 0)
);

create table if not exists public.sistema_configuracion (
    clave text primary key,
    valor text not null,
    descripcion text,
    updated_at timestamptz not null default now()
);

insert into public.sistema_configuracion (clave, valor, descripcion)
values
    ('precio_pelon', '190', 'Precio base de un pelon para Calcupelones.'),
    ('stock_bajo_productos', '5', 'Umbral para alertar productos con stock bajo.'),
    ('stock_bajo_hilos', '5', 'Umbral para alertar hilos con stock bajo.'),
    ('whatsapp_negocio', '51999999999', 'Numero de WhatsApp del negocio en formato internacional.')
on conflict (clave) do nothing;

create table if not exists public.historial_estados_cotizacion (
    id_historial bigint generated by default as identity primary key,
    id_pedido bigint not null references public.pedidos_cotizacion(id_pedido) on delete cascade,
    estado_anterior text,
    estado_nuevo text not null,
    cambiado_por uuid references auth.users(id),
    creado_at timestamptz not null default now()
);

create or replace function public.fn_registrar_venta_sistema(
    p_id_cliente bigint,
    p_id_producto bigint,
    p_id_metodo_pago bigint,
    p_cantidad integer,
    p_fecha_venta date,
    p_observacion text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
    v_stock integer;
    v_precio numeric(12, 2);
    v_id_venta bigint;
begin
    if not public.fn_es_admin() then
        raise exception 'No autorizado';
    end if;

    if p_cantidad is null or p_cantidad <= 0 then
        raise exception 'La cantidad debe ser mayor a cero';
    end if;

    select stock, precio
    into v_stock, v_precio
    from public.sistema_productos
    where id_producto = p_id_producto
    for update;

    if not found then
        raise exception 'Producto no encontrado';
    end if;

    if v_stock < p_cantidad then
        raise exception 'No hay suficiente stock para realizar esta venta';
    end if;

    update public.sistema_productos
    set stock = stock - p_cantidad
    where id_producto = p_id_producto;

    insert into public.sistema_ventas (
        id_cliente,
        id_producto,
        id_metodo_pago,
        cantidad,
        precio_unitario,
        fecha_venta,
        observacion
    )
    values (
        p_id_cliente,
        p_id_producto,
        p_id_metodo_pago,
        p_cantidad,
        v_precio,
        coalesce(p_fecha_venta, current_date),
        p_observacion
    )
    returning id_venta into v_id_venta;

    return v_id_venta;
end;
$$;

create or replace function public.fn_anular_venta_sistema(p_id_venta bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
    v_venta public.sistema_ventas%rowtype;
begin
    if not public.fn_es_admin() then
        raise exception 'No autorizado';
    end if;

    select *
    into v_venta
    from public.sistema_ventas
    where id_venta = p_id_venta
    for update;

    if not found then
        raise exception 'Venta no encontrada';
    end if;

    if v_venta.anulada then
        raise exception 'La venta ya esta anulada';
    end if;

    update public.sistema_ventas
    set anulada = true
    where id_venta = p_id_venta;

    update public.sistema_productos
    set stock = stock + v_venta.cantidad
    where id_producto = v_venta.id_producto;
end;
$$;

do $$
declare
    item record;
begin
    for item in
        select table_name
        from information_schema.tables
        where table_schema = 'public'
          and table_name in (
            'sistema_clientes',
            'sistema_productos',
            'sistema_ventas',
            'sistema_configuracion'
          )
    loop
        execute format('drop trigger if exists trg_%I_updated_at on public.%I', item.table_name, item.table_name);
        execute format('create trigger trg_%I_updated_at before update on public.%I for each row execute function public.fn_actualizar_updated_at()', item.table_name, item.table_name);
    end loop;
end;
$$;

alter table public.sistema_clientes enable row level security;
alter table public.sistema_productos enable row level security;
alter table public.sistema_metodos_pago enable row level security;
alter table public.sistema_ventas enable row level security;
alter table public.sistema_configuracion enable row level security;
alter table public.historial_estados_cotizacion enable row level security;

drop policy if exists "Admins gestionan clientes internos" on public.sistema_clientes;
drop policy if exists "Admins gestionan productos internos" on public.sistema_productos;
drop policy if exists "Admins leen metodos de pago" on public.sistema_metodos_pago;
drop policy if exists "Admins gestionan ventas internas" on public.sistema_ventas;
drop policy if exists "Admins gestionan configuracion" on public.sistema_configuracion;
drop policy if exists "Admins leen historial de cotizaciones" on public.historial_estados_cotizacion;
drop policy if exists "Admins registran historial de cotizaciones" on public.historial_estados_cotizacion;

create policy "Admins gestionan clientes internos"
on public.sistema_clientes
for all
to authenticated
using (public.fn_es_admin())
with check (public.fn_es_admin());

create policy "Admins gestionan productos internos"
on public.sistema_productos
for all
to authenticated
using (public.fn_es_admin())
with check (public.fn_es_admin());

create policy "Admins leen metodos de pago"
on public.sistema_metodos_pago
for select
to authenticated
using (public.fn_es_admin());

create policy "Admins gestionan ventas internas"
on public.sistema_ventas
for all
to authenticated
using (public.fn_es_admin())
with check (public.fn_es_admin());

create policy "Admins gestionan configuracion"
on public.sistema_configuracion
for all
to authenticated
using (public.fn_es_admin())
with check (public.fn_es_admin());

create policy "Admins leen historial de cotizaciones"
on public.historial_estados_cotizacion
for select
to authenticated
using (public.fn_es_admin());

create policy "Admins registran historial de cotizaciones"
on public.historial_estados_cotizacion
for insert
to authenticated
with check (public.fn_es_admin());

alter table public.sistema_clientes replica identity full;
alter table public.sistema_productos replica identity full;
alter table public.sistema_ventas replica identity full;
alter table public.historial_estados_cotizacion replica identity full;

do $$
begin
    alter publication supabase_realtime add table public.sistema_clientes;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.sistema_productos;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.sistema_ventas;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.historial_estados_cotizacion;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;
