create or replace function public.fn_actualizar_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.inventario_hilos (
    id_hilo bigint generated by default as identity primary key,
    codigo_hilo text not null unique,
    nombre_color text not null,
    marca text not null,
    stock integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint inventario_hilos_marca_check check (marca in ('Lumina', 'Polifill', 'Polineon')),
    constraint inventario_hilos_stock_check check (stock >= 0)
);

drop trigger if exists trg_inventario_hilos_updated_at on public.inventario_hilos;

create trigger trg_inventario_hilos_updated_at
before update on public.inventario_hilos
for each row
execute function public.fn_actualizar_updated_at();

alter table public.inventario_hilos enable row level security;

create policy "Admins gestionan inventario de hilos"
on public.inventario_hilos
for all
to authenticated
using (
    exists (
        select 1
        from public.admins
        where admins.user_id = auth.uid()
    )
)
with check (
    exists (
        select 1
        from public.admins
        where admins.user_id = auth.uid()
    )
);

create table if not exists public.pelones (
    tipo_pelon text primary key,
    estado text not null default 'normal',
    updated_at timestamptz not null default now(),
    constraint pelones_tipo_check check (
        tipo_pelon in ('Pelon Desgarrable', 'Pelon Direccional', 'Pelon Galleta')
    ),
    constraint pelones_estado_check check (
        estado in ('casi nada', 'poco', 'normal', 'mucho', 'completo')
    )
);

drop trigger if exists trg_pelones_updated_at on public.pelones;

create trigger trg_pelones_updated_at
before update on public.pelones
for each row
execute function public.fn_actualizar_updated_at();

alter table public.pelones enable row level security;

create policy "Admins gestionan pelones"
on public.pelones
for all
to authenticated
using (
    exists (
        select 1
        from public.admins
        where admins.user_id = auth.uid()
    )
)
with check (
    exists (
        select 1
        from public.admins
        where admins.user_id = auth.uid()
    )
);

insert into public.pelones (tipo_pelon, estado)
values
    ('Pelon Desgarrable', 'normal'),
    ('Pelon Direccional', 'normal'),
    ('Pelon Galleta', 'normal')
on conflict (tipo_pelon) do nothing;

alter table public.pedidos_cotizacion replica identity full;
alter table public.inventario_hilos replica identity full;
alter table public.pelones replica identity full;

do $$
begin
    alter publication supabase_realtime add table public.pedidos_cotizacion;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.inventario_hilos;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.pelones;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;
